import Link from "next/link";import ExtensionScreenshots from "../ExtensionScreenshots";
export const metadata={title:"Page Capture Onboarding"};
const phases=[
  ["01","Install and pin","Download the current ZIP, extract it, load the folder from chrome://extensions, and pin Page Capture beside the address bar."],
  ["02","Run a fictional-data test","Open the Test Lab, choose an application, open the extension, and name the test without using a patient or provider name."],
  ["03","Choose safeguards","Keep Pause and skip for sensitive screens during the pilot. Use Blur and capture only after reviewing how the target portal labels sensitive fields."],
  ["04","Work through the portal","Complete each page normally. Page Capture saves and verifies the visible page before allowing a recognized Next action."],
  ["05","Review the evidence","Finish the test, inspect saved and skipped pages, add notes, and remove any screenshot that should not be retained."],
  ["06","Approve the portal","Create the pilot-readiness report. Investigate warnings and repeat the test before authorizing real information."],
];
export default function Onboarding(){return <main className="info-page"><nav className="nav-shell"><Link className="brand" href="/"><span className="brand-mark"><i/></span><span><strong>Page Capture</strong><small>Onboarding</small></span></Link><div className="nav-links"><Link href="/product">Product</Link><Link href="/tutorials">Tutorials</Link><Link href="/test-lab">Test Lab</Link><Link href="/download">Download</Link></div></nav><header className="info-hero compact-hero"><p className="kicker"><span>●</span> Start here</p><h1>From download to<br/><em>approved pilot.</em></h1><p>Follow this sequence once for every new portal. It explains what to click, what to review, and when the result is safe enough to expand.</p><div className="hero-actions"><Link className="button primary" href="/download">Download the extension</Link><Link className="button text-button" href="/test-lab">Open the Test Lab</Link></div></header><div className="onboarding-manual"><ExtensionScreenshots/></div><section className="onboarding-path">{phases.map(([n,title,text])=><article key={n}><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></article>)}</section><section className="decision-gate"><div><p className="overline light">Production gate</p><h2>Do not use real data until all four are true.</h2></div><ul><li>Every expected page was captured or intentionally skipped.</li><li>Transitions were confirmed without duplicate screenshots.</li><li>Sensitive-page behavior was reviewed on the target portal.</li><li>The readiness report has no unexplained failures or blocked events.</li></ul></section><section className="onboarding-tools"><h2>Where each tool fits.</h2><div>{[["Session note","Record an exception or follow-up without changing the screenshot."],["Sensitive mode","Pause, redact detected visible fields, or capture—pause is the safest pilot default."],["Portal profile","Save working Next labels and settings for a portal you have tested."],["Support report","Share extension behavior without screenshots, answers, case labels, or full URLs."],["Readiness report","Summarize saves, skips, failures, and confirmed transitions; print it as a PDF."],["Session recovery","Reopen the extension on the same tab after a popup closes or the page reloads."]].map(([a,b])=><article key={a}><strong>{a}</strong><p>{b}</p></article>)}</div></section></main>}
