import Link from "next/link";
export const metadata={title:"Production Readiness — Page Capture"};
const checks=[
  ["Screenshot integrity","Implemented","Image decoding, minimum dimensions, blank-image detection, then completed-download verification."],
  ["Navigation transaction","Implemented","Every supported Next action is journaled from frozen page through capture, storage, release, and confirmation."],
  ["Page-change proof","Implemented","At least two independent signals must confirm the new step: URL, content fingerprint, heading, forms, controls, or detached action."],
  ["Interruption recovery","Implemented","Unfinished transactions become a visible anomaly after restart. Capture remains paused until a person reviews the page."],
  ["Portal profiles","Controlled pilot","Portal settings expire after 30 days and must be reviewed again."],
  ["Arbitrary portals","Not certified","Cross-origin frames, browser-protected pages, CAPTCHAs, unusual controls, and portal redesigns still require supervision and portal validation."],
];
export default function Readiness(){return <main className="info-page"><nav className="nav-shell"><Link className="brand" href="/"><span className="brand-mark"><i/></span><span><strong>Page Capture</strong><small>Readiness ledger</small></span></Link><div className="nav-links"><Link href="/product">Product</Link><Link href="/test-lab">Test Lab</Link><Link href="/compatibility">Compatibility</Link><Link className="active-tab" href="/readiness">Readiness</Link><Link href="/download">Download</Link></div></nav><header className="info-hero compact-hero"><p className="kicker"><span>●</span> Production boundary</p><h1>Evidence before<br/><em>automation.</em></h1><p>Version 1.2 fails closed when it cannot prove that a page was captured and the application moved forward. It is ready for supervised, allowlisted portal pilots—not unattended use across every portal.</p></header><section className="readiness-ledger"><header><span>Control</span><span>Current state</span><span>Evidence and limit</span></header>{checks.map(([name,state,detail])=><article key={name}><strong>{name}</strong><b className={state==="Not certified"?"not-ready":state==="Controlled pilot"?"pilot":"ready"}>{state}</b><p>{detail}</p></article>)}</section><section className="evidence-note"><strong>Recommended release gate</strong><p>Run 30 complete applications per allowlisted portal with zero silent misses, review every anomaly, then approve that portal and version pair for limited production.</p><Link href="/test-lab">Start in the Test Lab →</Link></section></main>}
