import Link from "next/link";
export const metadata={title:"Page Capture Product"};
const clips=[
  {src:"/demos/capture.webm",poster:"/demos/capture-poster.png",label:"Automatic capture",title:"The page is saved first.",text:"Page Capture holds the forward action until the screenshot is created and verified."},
  {src:"/demos/sensitive.webm",poster:"/demos/sensitive-poster.png",label:"Sensitive-page safeguard",title:"Risky screens pause.",text:"Recognizable password, payment, SSN, and verification-code fields stop automatic capture."},
  {src:"/demos/record.webm",poster:"/demos/record-poster.png",label:"Local evidence folder",title:"The record stays readable.",text:"Numbered images and a session summary are grouped in a new folder for each test."},
  {src:"/demos/fullpage.webm",poster:"/demos/fullpage-poster.png",label:"Entire-page mode",title:"Long pages become one record.",text:"Optional entire-page capture scrolls and stitches sections into a single verified image."},
  {src:"/demos/duplicate.webm",poster:"/demos/duplicate-poster.png",label:"Duplicate protection",title:"Repeat clicks do not create clutter.",text:"Rapid duplicate actions keep the first verified screenshot instead of saving extra copies."},
  {src:"/demos/newsession.webm",poster:"/demos/newsession-poster.png",label:"Fresh test folders",title:"Every run starts clean.",text:"A new session creates a separate timestamped folder, even when you reuse the same case label."},
];
export default function Product(){return <main className="info-page"><SiteNav active="Product"/><header className="info-hero"><p className="kicker"><span>â—</span> Product</p><h1>A screenshot record<br/><em>that builds itself.</em></h1><p>Page Capture verifies each screenshot before a licensing portal advances, then confirms that the page actually changed.</p><div className="hero-actions"><Link className="button primary" href="/download">Download v1.0</Link><Link className="button text-button" href="/test-lab">Run a safe test</Link></div></header><section className="film-premiere" aria-labelledby="demo-film-title"><div className="film-heading"><p className="overline light">Guided product film Â· 11 seconds</p><h2 id="demo-film-title">See the record build itself.</h2><p>This AI-produced interface animation follows the real Page Capture workflow. It uses fictional application data and does not depict a live government portal.</p></div><div className="film-player"><video controls preload="metadata" poster="/demos/overview-poster.png"><source src="/demos/overview.webm" type="video/webm"/><track default kind="captions" src="/demos/overview.vtt" srcLang="en" label="English"/>Your browser does not support embedded video.</video><span>Simulated product demo</span></div></section><section className="clip-gallery" aria-labelledby="feature-films"><div className="clip-intro"><p className="overline">Six moments to watch</p><h2 id="feature-films">What happens around every Next click.</h2><p>Short, silent loops isolate the moments that matter. Pause any clip to inspect the interface.</p></div><div className="clip-grid">{clips.map(clip=><article className="clip-card" key={clip.title}><video muted loop autoPlay playsInline preload="metadata" poster={clip.poster} aria-label={`${clip.label} simulated demonstration`}><source src={clip.src} type="video/webm"/></video><div><span>{clip.label}</span><h3>{clip.title}</h3><p>{clip.text}</p></div></article>)}</div></section><section className="state-story"><div><p className="overline">The operational loop</p><h2>Five checks around every click.</h2></div>{["Detect forward intent","Assess portal confidence","Capture and verify the file","Allow the portal to advance","Confirm the next page appeared"].map((x,i)=><article key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></article>)}</section><section className="audience-paths"><h2>Built for work that needs a record.</h2><div>{["Licensing teams","Credentialing teams","Insurance enrollment","Compliance and audits","Website QA"].map(x=><article key={x}><strong>{x}</strong><p>Keep a numbered local record of each completed step without interrupting the workflow.</p></article>)}</div></section><SiteFooter/></main>}
function SiteNav({active}:{active:string}){return <nav className="nav-shell"><Link className="brand" href="/"><span className="brand-mark"><i/></span><span><strong>Page Capture</strong><small>Verified capture workflow</small></span></Link><div className="nav-links">{["Product","Test Lab","Compatibility","Help","Download"].map(x=><Link className={x===active?"active-tab":""} key={x} href={x==="Test Lab"?"/test-lab":"/"+x.toLowerCase()}>{x}</Link>)}</div></nav>}
function SiteFooter(){return <footer className="site-footer"><p>Local-first tooling for application records.</p><div><Link href="/privacy">Privacy</Link><Link href="/security">Security</Link><Link href="/changelog">Changelog</Link></div></footer>}
