import Link from "next/link";
export const metadata={title:"Page Capture Product"};
const clips=[
  {src:"/demos/capture.webm",poster:"/demos/capture-poster.png",label:"Automatic capture",title:"Save before continuing",text:"The extension holds the forward action until the screenshot is created and verified."},
  {src:"/demos/sensitive.webm",poster:"/demos/sensitive-poster.png",label:"Sensitive-page safeguard",title:"Pause on detected sensitive fields",text:"Password, payment, SSN, and verification-code fields can pause automatic capture."},
  {src:"/demos/record.webm",poster:"/demos/record-poster.png",label:"Local evidence folder",title:"Keep the record together",text:"Numbered images and a session summary are grouped in a new folder for each test."},
  {src:"/demos/fullpage.webm",poster:"/demos/fullpage-poster.png",label:"Entire-page mode",title:"Capture long pages",text:"Optional entire-page capture scrolls and stitches sections into one image."},
  {src:"/demos/duplicate.webm",poster:"/demos/duplicate-poster.png",label:"Duplicate protection",title:"Ignore repeat clicks",text:"Rapid duplicate actions keep the first verified screenshot instead of saving another copy."},
  {src:"/demos/newsession.webm",poster:"/demos/newsession-poster.png",label:"Fresh test folders",title:"Separate each run",text:"A new session creates a separate timestamped folder, even when a case label is reused."},
];
export default function Product(){return <main className="info-page"><SiteNav/><header className="info-hero"><p className="kicker"><span>●</span> Product</p><h1>Capture each application page before moving forward.</h1><p>Page Capture verifies each screenshot before a licensing portal advances, then confirms that the page changed.</p><div className="hero-actions"><Link className="button primary" href="/download">Download v1.1</Link><Link className="button text-button" href="/tutorials">Read the tutorials</Link></div></header><section className="film-premiere" aria-labelledby="demo-film-title"><div className="film-heading"><p className="overline light">Workflow demonstration · 11 seconds</p><h2 id="demo-film-title">Capture, verify, continue.</h2><p>This simulated interface demonstration uses fictional data. It shows the workflow, not a live government portal.</p></div><div className="film-player"><video controls preload="metadata" poster="/demos/overview-poster.png"><source src="/demos/overview.webm" type="video/webm"/><track default kind="captions" src="/demos/overview.vtt" srcLang="en" label="English"/>Your browser does not support embedded video.</video><span>Simulated product demo</span></div></section><section className="clip-gallery" aria-labelledby="feature-films"><div className="clip-intro"><p className="overline">Feature demonstrations</p><h2 id="feature-films">Inspect one behavior at a time.</h2><p>Each clip is paused by default. Use the controls when you want to review a specific feature.</p></div><div className="clip-grid">{clips.map(clip=><article className="clip-card" key={clip.title}><video muted loop controls playsInline preload="none" poster={clip.poster} aria-label={`${clip.label} simulated demonstration`}><source src={clip.src} type="video/webm"/></video><div><span>{clip.label}</span><h3>{clip.title}</h3><p>{clip.text}</p></div></article>)}</div></section><section className="state-story"><div><p className="overline">Capture sequence</p><h2>Five checks around every forward action.</h2></div>{["Detect forward intent","Assess portal confidence","Capture and verify the file","Allow the portal to advance","Confirm the next page appeared"].map((x,i)=><article key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></article>)}</section><SiteFooter/></main>}
function SiteNav(){return <nav className="nav-shell"><Link className="brand" href="/"><span className="brand-mark"><i/></span><span><strong>Page Capture</strong><small>Application record utility</small></span></Link><div className="nav-links"><Link className="active-tab" href="/product">Product</Link><Link href="/tutorials">Tutorials</Link><Link href="/test-lab">Test Lab</Link><Link href="/compatibility">Compatibility</Link><Link href="/download">Download</Link></div></nav>}
function SiteFooter(){return <footer className="site-footer"><p>Local-first tooling for application records.</p><div><Link href="/onboarding">Onboarding</Link><Link href="/privacy">Privacy</Link><Link href="/changelog">Changelog</Link></div></footer>}
