import Link from "next/link";
import { CaptureDemo } from "../CaptureDemo";

export const metadata = {
  title: "Page Capture Test Lab â€” No-login template forms",
  description: "Test Page Capture with fictional licensing, credentialing, and insurance template forms.",
};

export default function TestLab() {
  return <main className="test-lab-page">
    <nav className="nav-shell lab-nav" aria-label="Main navigation">
      <Link className="brand" href="/" aria-label="Page Capture home"><span className="brand-mark" aria-hidden="true"><i /></span><span><strong>Page Capture</strong><small>for licensing applications</small></span></Link>
      <div className="nav-links"><Link href="/">Home</Link><a className="active-tab" href="#forms">Test lab</a><a href="#troubleshooting">Help</a><Link className="nav-cta" href="/download">Download v1.0</Link></div>
    </nav>

    <header className="lab-hero">
      <div><p className="kicker"><span>â—</span> Safe testing workspace</p><h1>Put every capture mode<br /><em>through its paces.</em></h1><p>Use fictional, multi-page forms to verify automatic capture, full-page stitching, varied navigation labels, sensitive-screen skipping, and the completion review.</p></div>
      <ol className="lab-checklist"><li><span>1</span><div><strong>Start Page Capture</strong><small>Name the test and choose visible-area or full-page mode.</small></div></li><li><span>2</span><div><strong>Choose a template</strong><small>Licensing, credentialing, or insurance enrollment.</small></div></li><li><span>3</span><div><strong>Advance every page</strong><small>Compare the extension record with the expected record.</small></div></li></ol>
    </header>

    <nav className="lab-section-nav" aria-label="Test Lab sections"><a href="#forms">Applications</a><a href="#guide">Checklist</a><a href="#gallery">Extension gallery</a><a href="#scorecard">Test status</a><a href="#troubleshooting">Help</a></nav>

    <section className="lab-workbench" id="forms">
      <div className="lab-heading"><p className="overline">Application test catalog</p><h2>Choose a complete test application.</h2><p>Each listed test contains a separate multi-page template and tells you which capture behavior it exercises. Everything is fictional and nothing is submitted.</p></div>
      <CaptureDemo />
    </section>

    <section className="lab-results"><div><p className="overline light">What success looks like</p><h2>A complete record without a missed page.</h2></div><ul><li>Each ordinary step creates one screenshot</li><li>Long pages produce a readable full-page image</li><li>The verification or payment step is skipped</li><li>Finishing the test shows thumbnails and totals</li><li>Removing a screenshot deletes its local file</li></ul></section>

    <section className="lab-guide" id="guide">
      <div className="lab-heading"><p className="overline">Guided test checklist</p><h2>One run tells you whether the basics work.</h2><p>Use this sequence with any application above. Keep the extension open at the end so you can compare its record with the expected result.</p></div>
      <ol className="run-checklist"><li><span>01</span><div><strong>Start a fresh session</strong><p>Use a test-only case label and confirm the status changes to Capturing.</p></div></li><li><span>02</span><div><strong>Advance all six steps</strong><p>Try visible-area mode first, then repeat in full-page mode.</p></div></li><li><span>03</span><div><strong>Confirm the protected step</strong><p>The verification or payment page should be recorded as skipped, with no screenshot saved.</p></div></li><li><span>04</span><div><strong>Review and export</strong><p>Check the thumbnails and totals, open the saved folder, then create the HTML summary.</p></div></li></ol>
    </section>

    <section className="extension-gallery" id="gallery"><div className="lab-heading"><p className="overline">Extension gallery</p><h2>Know what each state should look like.</h2><p>The popup changes with the job: prepare a test, monitor captures, handle a protected page, then review the finished record.</p></div><div className="gallery-states"><article><span>Ready</span><div className="mini-popup"><b>Set up test</b><strong>What should this test be called?</strong><i>Utah RN test</i><button>Start test</button></div></article><article><span>Capturing</span><div className="mini-popup"><b className="green">â— Capturing</b><strong>Utah RN test</strong><i>03 Education history Â· Saved</i><button>Finish test</button></div></article><article><span>Protected</span><div className="mini-popup"><b className="amber">â€” Sensitive page skipped</b><strong>Identity verification</strong><i>No screenshot was created</i><button>Continue safely</button></div></article><article><span>Complete</span><div className="mini-popup"><b className="green">âœ“ Test complete</b><strong>5 saved Â· 1 skipped</strong><i>Review thumbnails and totals</i><button>Open screenshots</button></div></article></div></section>

    <section className="test-scorecard" id="scorecard"><div><p className="overline light">Public testing scorecard</p><h2>Evidence, not a blanket promise.</h2><p>This preview is ready for controlled fictional-data pilots. Real portals can use custom controls and protections we have not encountered yet.</p></div><div className="score-grid"><article><strong>18</strong><span>Automated checks passing</span></article><article><strong>2</strong><span>Browsers supported</span></article><article><strong>3</strong><span>Complete application simulations</span></article><article><strong>Pilot</strong><span>Current readiness level</span></article></div><div className="tested-sites"><strong>Verified here</strong><span>Test Lab forms</span><span>Long scrolling pages</span><span>Sensitive-field skips</span><span>Custom button labels</span><b>Real licensing portals: validation in progress</b></div></section>

    <section className="output-preview" aria-labelledby="output-title"><div><p className="overline light">Sample output</p><h2 id="output-title">A tidy record, ready to review.</h2><p>Every session receives its own folder. Names stay sequential even when a sensitive page is skipped.</p></div><div className="folder-window"><div className="folder-bar"><span>Downloads</span><b>â€º License Page Captures â€º TEST-UT-NP</b></div><ul><li><i>PNG</i><span><strong>01_applicant-profile.png</strong><small>Screenshot Â· 10:42 AM</small></span><b>Saved</b></li><li><i>PNG</i><span><strong>02_education-history.png</strong><small>Full page Â· 10:44 AM</small></span><b>Saved</b></li><li className="folder-skip"><i>â€”</i><span><strong>identity-verification</strong><small>Sensitive page Â· no image created</small></span><b>Skipped</b></li><li><i>HTML</i><span><strong>session-summary.html</strong><small>Capture record and timestamps</small></span><b>Exported</b></li></ul></div></section>

    <section className="lab-library"><div className="lab-heading"><p className="overline">Behavior coverage</p><h2>Test more than the happy path.</h2><p>These checks represent the portal patterns Page Capture is designed to handle.</p></div><div className="feature-matrix"><article><span>Navigation</span><strong>Next, Continue, Proceed, Review</strong><p>Common text labels and your own custom labels.</p></article><article><span>Page length</span><strong>Visible area and full page</strong><p>Short forms, scrolling forms, and stitched captures.</p></article><article><span>Safety</span><strong>Sensitive-screen pause</strong><p>Password, SSN, payment, and verification language.</p></article><article><span>Quality</span><strong>Duplicate-click protection</strong><p>Rapid clicks should create only one screenshot.</p></article><article><span>Movement</span><strong>Back and forward navigation</strong><p>Only forward progress triggers automatic capture.</p></article><article><span>Boundaries</span><strong>Domain-change protection</strong><p>A session stops before following an unexpected domain.</p></article></div></section>

    <section className="compat-panel"><div><p className="overline">Compatibility</p><h2>Built for ordinary browser workflows.</h2></div><div className="compat-table"><div><strong>Chrome</strong><span>Supported</span><small>Developer-mode install</small></div><div><strong>Microsoft Edge</strong><span>Supported</span><small>Developer-mode install</small></div><div><strong>Firefox and Safari</strong><span className="muted-status">Not yet</span><small>No packaged version</small></div><div><strong>Settings, PDFs, extension stores</strong><span className="muted-status">Restricted</span><small>Browsers block capture on protected pages</small></div></div></section>

    <section className="privacy-explainer"><div><p className="overline light">Privacy walkthrough</p><h2>What stays localâ€”and what to check.</h2><p>Page Capture does not upload screenshots or application answers. It saves files through your browser into Downloads. If that folder is synchronized by OneDrive or another service, that service may copy the files.</p><a href="/privacy">Read the full privacy notice â†’</a></div><ol><li><span>1</span><strong>You start each session</strong></li><li><span>2</span><strong>The current tab is observed for navigation</strong></li><li><span>3</span><strong>Images save to your device</strong></li><li><span>4</span><strong>Sensitive screens are skipped when detected</strong></li></ol></section>

    <section className="support-grid" id="troubleshooting"><div><p className="overline">Troubleshooting</p><h2>Fast fixes for the most common snags.</h2><details><summary>Start capturing does not change the status<span>+</span></summary><p>Reload the application tab after installing or updating the extension, then reopen Page Capture and start a new session.</p></details><details><summary>Moving forward does not save a screenshot<span>+</span></summary><p>Add the portalâ€™s exact button text under custom navigation labels. Icon-only controls may need a portal-specific rule.</p></details><details><summary>No file appears in Downloads<span>+</span></summary><p>Check the extension ledger for a failed or skipped event, then confirm Chrome or Edge is allowed to download files.</p></details><details><summary>A safe page is being skipped<span>+</span></summary><p>Look for password, SSN, payment, or verification wording on the page. Turn off sensitive-screen pause only with an approved fictional test.</p></details></div><aside className="report-card"><p className="overline light">Report a test result</p><h3>Found a portal pattern we should support?</h3><p>Tell us the website, button label, expected result, and what happened. Do not attach real applicant information.</p><a className="button inverse" href="https://github.com/draphael123/license-page-capture/issues/new?template=portal.yml">Open the issue form â†’</a><small>Include the browser and Page Capture version. A screenshot is optional.</small></aside></section>

    <section className="use-release"><div><p className="overline">More ways to use it</p><h2>Any multi-step web record can benefit.</h2><div className="use-tags"><span>Credentialing</span><span>Insurance enrollment</span><span>Employee onboarding</span><span>Audit walkthroughs</span><span>Reimbursement portals</span><span>Website QA</span></div></div><aside><p className="overline">Current release</p><strong>Page Capture v1.0.0</strong><span>Developer preview Â· updated August 13, 2026</span><ul><li>Fresh folder for every session</li><li>Full-page stitching</li><li>Capture review and deletion</li><li>Update availability checks</li></ul><a href="/changelog">Read the changelog â†’</a></aside></section>

    <footer className="site-footer"><div className="brand"><span className="brand-mark" aria-hidden="true"><i /></span><span><strong>Page Capture</strong><small>Test lab Â· fictional data only</small></span></div><p>No information on this page is submitted.</p><div><Link href="/privacy">Privacy</Link><Link href="/security">Security</Link><Link href="/">Home</Link></div></footer>
  </main>;
}
