"use client";
import {useMemo,useState} from "react";
const tutorials=[
 {track:"Install",title:"Install in Chrome or Edge",time:"3 min",summary:"Download, extract, load the extension, and pin it.",steps:["Download the current ZIP from the Download page.","Extract the ZIP to a folder you will keep.","Open chrome://extensions or edge://extensions and enable Developer mode.","Choose Load unpacked and select the extracted folder.","Pin Page Capture beside the address bar, then open the Test Lab."]},
 {track:"Install",title:"Update an unpacked installation",time:"2 min",summary:"Replace the old folder without losing your saved screenshots.",steps:["Finish any active capture session.","Download and extract the new release.","Replace the old extension folder with the new files.","Open the browser extensions page and select Reload.","Confirm the version shown in Page Capture, then run a fictional-data test."]},
 {track:"First test",title:"Run your first Test Lab application",time:"5 min",summary:"Practice the complete workflow with fictional information.",steps:["Open Test Lab and choose Nurse licensing.","Open Page Capture and complete the four-step introduction.","Name the test First test; keep sensitive pages set to Pause and skip.","Select Start test and complete each form page.","Finish the test, inspect the activity list, and create a readiness report."]},
 {track:"Daily use",title:"Start, capture, and finish a record",time:"4 min",summary:"The standard workflow for a previously approved portal.",steps:["Open the first application page before starting Page Capture.","Use a non-sensitive test name and confirm the saved portal profile.","Work normally; wait for the saved confirmation before leaving a page.","Use Capture current page only when a page has no recognized forward control.","Finish the session and review every saved, skipped, or failed event."]},
 {track:"Daily use",title:"Use entire-page capture",time:"2 min",summary:"Save a long form as one stitched image.",steps:["Open Settings and tools before starting the test.","Enable Capture the entire page.","Expect a short pause while the page scrolls.","Review the resulting image for sticky headers or dynamic content.","Turn the setting off for portals where scrolling changes the form."]},
 {track:"Daily use",title:"Add notes and remove a screenshot",time:"2 min",summary:"Document exceptions and correct the local record.",steps:["During capture, type a concise operational note and select Add note.","Do not put personal information in a note.","After finishing, inspect the thumbnail and status for each event.","Select Remove only when a retained screenshot should be deleted.","Create a new readiness report after changing the record."]},
 {track:"Privacy",title:"Choose a sensitive-page mode",time:"3 min",summary:"Understand Pause, Redact, and Capture before using them.",steps:["Use Pause and skip for a portal’s first pilot.","Use Blur detected fields only for a supervised test.","Open every redacted screenshot and confirm that all sensitive content is covered.","Remember that text outside recognized form fields may remain visible.","Use Capture without redaction only when your organization has explicitly approved it."]},
 {track:"Privacy",title:"Create and save a readiness report",time:"2 min",summary:"Produce an approval record that can be printed to PDF.",steps:["Finish or pause after completing representative pages.","Open Settings and tools and choose Create pilot-readiness report.","Open the downloaded HTML report.","Review saved pages, confirmed transitions, skips, and issues.","Use Print and choose Save as PDF; store it under your normal retention policy."]},
 {track:"Privacy",title:"Export a privacy-safe support report",time:"1 min",summary:"Share behavior diagnostics without screenshots or answers.",steps:["Reproduce the problem with fictional data.","Choose Export privacy-safe support report.","Open the JSON file and confirm it contains no identifying information.","Attach it to a portal issue with the portal name and browser version."]},
 {track:"Troubleshooting",title:"Next was not detected",time:"3 min",summary:"Teach Page Capture a portal-specific forward control.",steps:["Open the extension before starting the session.","Expand Settings and tools.","Enter the exact visible label of the portal button under Additional Next-button labels.","Run preflight again and confirm Forward control says Found.","Save the profile by starting a fictional-data test."]},
 {track:"Troubleshooting",title:"No screenshot appeared",time:"3 min",summary:"Check browser access, downloads, and page restrictions.",steps:["Confirm the extension says Capturing and the page is in the same tab where the test started.","Reload the portal page and reopen the extension.","Check that the browser permits downloads and that the page is not a PDF viewer or browser setting.","Try Capture current page.","Export a support report if the problem continues."]},
 {track:"Troubleshooting",title:"Recover an interrupted session",time:"2 min",summary:"Resume after closing the popup or reloading a portal page.",steps:["Return to the same portal tab used to start the session.","Reload the page if the capture indicator is absent.","Open Page Capture; the active case and prior events should return.","Capture one fictional page and confirm numbering continues.","If the original tab was closed, start a new session so folders remain separate."]},
];
const tracks=["All","Install","First test","Daily use","Privacy","Troubleshooting"];
export default function TutorialLibrary(){const[q,setQ]=useState("");const[track,setTrack]=useState(()=>{if(typeof window==="undefined")return "All";const value=new URLSearchParams(window.location.search).get("track")||"All";return tracks.find(x=>x.toLowerCase().replace(/\s/g,"-")===value.toLowerCase())||"All"});const visible=useMemo(()=>tutorials.filter(t=>(track==="All"||t.track===track)&&`${t.title} ${t.summary} ${t.steps.join(" ")}`.toLowerCase().includes(q.toLowerCase())),[q,track]);return <><section className="tutorial-controls" aria-label="Tutorial filters"><label>Search tutorials<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Try redaction, update, or Next…"/></label><div role="group" aria-label="Tutorial tracks">{tracks.map(x=><button className={track===x?"selected":""} key={x} onClick={()=>setTrack(x)}>{x}</button>)}</div></section><section className="tutorial-list" aria-live="polite"><p>{visible.length} tutorials</p>{visible.map((tutorial,index)=><details id={tutorial.title.toLowerCase().replace(/[^a-z0-9]+/g,"-")} key={tutorial.title} open={index===0&&visible.length<5}><summary><span><b>{tutorial.track}</b><strong>{tutorial.title}</strong><small>{tutorial.summary}</small></span><em>{tutorial.time}</em></summary><ol>{tutorial.steps.map(step=><li key={step}>{step}</li>)}</ol></details>)}</section></>}
